name: CI/CD - auth-api

on:
  push:
    branches: [ "develop" ]
    paths:
      - "auth-api/**"
  pull_request:
    branches: [ "develop" ]
    paths:
      - "auth-api/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./auth-api
          push: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/auth-api:latest
            ${{ secrets.ECR_REGISTRY }}/auth-api:${{ github.sha }}
