name: CI Log Processor

on:
  push:
    branches: [ develop, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: cd log-message-processor && pip install -r requirements.txt

      - name: Run script
        run: cd log-message-processor && python main.py --help || true

      - name: Build Docker image
        run: docker build -t naysp/log-message-processor ./log-message-processor
