name: CI Todos API

on:
  push:
    branches: [ develop, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd todos-api && npm install

      - name: Run tests
        run: cd todos-api && npm test

      - name: Build Docker image
        run: docker build -t naysp/todos-api ./todos-api
